### ISSUE TITLE
Compiling on windows?

### ISSUE THREAD

**Issue by Mike77154** [superctr/adpcm#3]
Naybe I will do a noob question, but there is a way to compile this on windows for exe usage?

thanks in advance

**Comment by superctr** [comment]
use MinGW-w64 and build with `make`.

**Comment by Mike77154** [comment]
Ok I try to compile, but now the console just opens fastly and fastly closes



Win 8 (pre-8.1)
[https://www.mediafire.com/file/1z60c4j53m7g1iu/ADPCM_last_try.exe/file](url)

Any Idea?

**Comment by superctr** [comment]
This is a command line application, if you try to launch it as a GUI application (by clicking on the icon), it won't do anything.
