### ISSUE TITLE
Encoder/decoder for NEC μPD7759?

### ISSUE THREAD

**Issue by gammalogic** [superctr/adpcm#5]
I am trying to help someone who is working on a retrogaming project and we need to convert a set of audio samples to a format suitable for playback on the μPD7759 (in an emulator).

Do you have any information about the ADPCM format used by this chip and how the encoding differs from the other chips and industry standard algorithms, or can one of the formats your software supports already do this? We have tried using SoX and Audacity to generate data in the correct format but the playback is incorrect or distorted.

Thanks in advance for any help or suggestions.

**Comment by superctr** [comment]
[MAME source code](https://github.com/mamedev/mame/blob/master/src/devices/sound/upd7759.cpp) contains a description of the sample format.
